export type ResourceType = "guide" | "template" | "checklist" | "handbook";

export interface Resource {
  id: string;
  title: string;
  details: string;
  type: ResourceType;
  category: string;
  stage: string;
  downloads: number;
  format: string;
  tags: string[];
  img: string;
  rating: number;
  saved: number;
  downloadUrl?: string;
}

export const RESOURCES: Resource[] = [
  { id: "ig-1", title: "How to Start a Club", details: "Step-by-step process from idea validation to first meeting launch.", type: "guide", category: "Getting Started", stage: "Beginner", downloads: 342, format: "PDF", tags: ["basics", "admin"], img: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 92, downloadUrl: "/resources-pdfs/ig-1.pdf" },
  { id: "ig-2", title: "Club Constitution Template", details: "Write a constitution that will pass school approval on the first submission.", type: "template", category: "Getting Started", stage: "Beginner", downloads: 623, format: "DOCX", tags: ["constitution", "template"], img: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=600&q=80", rating: 4.9, saved: 187, downloadUrl: "/resources-pdfs/ig-2.pdf" },
  { id: "ig-3", title: "Faculty Advisor Requirements", details: "Checklist for advisor confirmation and school policy alignment.", type: "checklist", category: "Getting Started", stage: "Beginner", downloads: 215, format: "PDF", tags: ["advisor", "policy"], img: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 63, downloadUrl: "/resources-pdfs/ig-3.pdf" },
  { id: "ig-4", title: "School Approval Steps", details: "Submission sequence, review expectations, and publication conditions.", type: "guide", category: "Getting Started", stage: "Beginner", downloads: 189, format: "PDF", tags: ["approval", "submission"], img: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=600&q=80", rating: 4.3, saved: 47, downloadUrl: "/resources-pdfs/ig-4.pdf" },
  { id: "lo-1", title: "Social Media Best Practices", details: "Promote your club on Instagram, Discord, and other platforms effectively.", type: "guide", category: "Recruiting & Promoting", stage: "Growing", downloads: 567, format: "PDF", tags: ["social media", "promotion"], img: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 143, downloadUrl: "/resources-pdfs/lo-1.pdf" },
  { id: "lo-2", title: "Club Fair Preparation", details: "Everything you need for a successful club fair booth.", type: "checklist", category: "Recruiting & Promoting", stage: "Growing", downloads: 312, format: "PDF", tags: ["club fair", "recruiting"], img: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 88, downloadUrl: "/resources-pdfs/lo-2.pdf" },
  { id: "lo-3", title: "Member Retention Strategies", details: "Keep members engaged with events, recognition, and meaningful activities.", type: "guide", category: "Recruiting & Promoting", stage: "Growing", downloads: 245, format: "PDF", tags: ["retention", "engagement"], img: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80", rating: 4.4, saved: 71, downloadUrl: "/resources-pdfs/lo-3.pdf" },
  { id: "lo-4", title: "Recruitment Flyer Templates", details: "Customizable flyer designs for announcing your club to new students.", type: "template", category: "Recruiting & Promoting", stage: "Growing", downloads: 489, format: "PDF", tags: ["flyer", "design"], img: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 122, downloadUrl: "/resources-pdfs/lo-4.pdf" },
  { id: "ob-1", title: "Running Effective Meetings", details: "Agenda templates, parliamentary procedure basics, and engagement techniques.", type: "template", category: "Meetings & Operations", stage: "Active", downloads: 421, format: "DOCX", tags: ["meetings", "agenda"], img: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 104, downloadUrl: "/resources-pdfs/ob-1.pdf" },
  { id: "ob-2", title: "Meeting Minutes Template", details: "Standard format for documenting discussions and decisions at every meeting.", type: "template", category: "Meetings & Operations", stage: "Active", downloads: 445, format: "DOCX", tags: ["minutes", "documentation"], img: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 98, downloadUrl: "/resources-pdfs/ob-2.pdf" },
  { id: "ob-3", title: "Officer Roles & Responsibilities", details: "Define clear roles for President, VP, Secretary, Treasurer, and more.", type: "handbook", category: "Meetings & Operations", stage: "Active", downloads: 278, format: "PDF", tags: ["officers", "roles"], img: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 77, downloadUrl: "/resources-pdfs/ob-3.pdf" },
  { id: "ex-1", title: "Event Planning Toolkit", details: "Comprehensive checklists for planning club events of any size.", type: "template", category: "Events & Funding", stage: "Active", downloads: 398, format: "DOCX", tags: ["events", "planning"], img: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=600&q=80", rating: 4.9, saved: 156, downloadUrl: "/resources-pdfs/ex-1.pdf" },
  { id: "ex-2", title: "Fundraising Playbook", details: "Proven strategies including bake sales, sponsorships, and grant writing.", type: "guide", category: "Events & Funding", stage: "Active", downloads: 534, format: "PDF", tags: ["fundraising", "grants"], img: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 178, downloadUrl: "/resources-pdfs/ex-2.pdf" },
  { id: "ex-3", title: "Budget Management Sheet", details: "Track club finances, submit purchase requests, and maintain transparency.", type: "template", category: "Events & Funding", stage: "Active", downloads: 267, format: "DOCX", tags: ["budget", "finance"], img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80", rating: 4.4, saved: 83, downloadUrl: "/resources-pdfs/ex-3.pdf" },
  { id: "mc-1", title: "Succession Planning", details: "How to transition leadership smoothly when officers graduate or step down.", type: "guide", category: "Leadership & Legacy", stage: "Advanced", downloads: 98, format: "PDF", tags: ["succession", "leadership"], img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 55, downloadUrl: "/resources-pdfs/mc-1.pdf" },
  { id: "mc-2", title: "Annual Report Template", details: "End-of-year report template showcasing achievements and impact.", type: "template", category: "Leadership & Legacy", stage: "Advanced", downloads: 187, format: "DOCX", tags: ["annual report", "impact"], img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 69, downloadUrl: "/resources-pdfs/mc-2.pdf" },
  { id: "mc-3", title: "Competition Prep Timeline", details: "12-week countdown with weekly milestones and practice schedules.", type: "guide", category: "Leadership & Legacy", stage: "Advanced", downloads: 201, format: "PDF", tags: ["competition", "prep"], img: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 91, downloadUrl: "/resources-pdfs/mc-3.pdf" },
  { id: "mc-4", title: "Judging Criteria Overview", details: "Understand how TSA and other organizations score student projects.", type: "handbook", category: "Leadership & Legacy", stage: "Advanced", downloads: 234, format: "PDF", tags: ["judging", "TSA"], img: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 112, downloadUrl: "/resources-pdfs/mc-4.pdf" },

  // â”€â”€ Getting Started Ã— Growing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "gs-g1", title: "Member Welcome Packet", details: "Onboarding template to welcome and orient new members joining your growing club.", type: "template", category: "Getting Started", stage: "Growing", downloads: 178, format: "DOCX", tags: ["onboarding", "welcome"], img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 58, downloadUrl: "/resources-pdfs/gs-g1.pdf" },
  // â”€â”€ Getting Started Ã— Active â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "gs-a1", title: "Club Charter Renewal Guide", details: "Annual process for renewing your school-approved charter and updating club documentation.", type: "guide", category: "Getting Started", stage: "Active", downloads: 145, format: "PDF", tags: ["charter", "renewal", "admin"], img: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=600&q=80", rating: 4.4, saved: 41, downloadUrl: "/resources-pdfs/gs-a1.pdf" },
  // â”€â”€ Getting Started Ã— Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "gs-ad1", title: "Multi-Chapter Coordination Guide", details: "How to coordinate with sister chapters, share resources, and maintain consistent standards.", type: "handbook", category: "Getting Started", stage: "Advanced", downloads: 89, format: "PDF", tags: ["multi-chapter", "coordination"], img: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 33, downloadUrl: "/resources-pdfs/gs-ad1.pdf" },

  // â”€â”€ Recruiting & Promoting Ã— Beginner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "rp-b1", title: "First 10 Members Playbook", details: "Practical tactics for recruiting your founding members from scratch before your first official meeting.", type: "guide", category: "Recruiting & Promoting", stage: "Beginner", downloads: 263, format: "PDF", tags: ["founding", "recruiting", "beginner"], img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 79, downloadUrl: "/resources-pdfs/rp-b1.pdf" },
  // â”€â”€ Recruiting & Promoting Ã— Active â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "rp-a1", title: "Partnership Outreach Templates", details: "Email and pitch templates for forming partnerships with other clubs, local organizations, and schools.", type: "template", category: "Recruiting & Promoting", stage: "Active", downloads: 201, format: "DOCX", tags: ["partnerships", "outreach"], img: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 62, downloadUrl: "/resources-pdfs/rp-a1.pdf" },
  // â”€â”€ Recruiting & Promoting Ã— Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "rp-ad1", title: "Alumni Engagement Handbook", details: "Strategies for building a long-term alumni network that mentors current members and supports the club.", type: "handbook", category: "Recruiting & Promoting", stage: "Advanced", downloads: 113, format: "PDF", tags: ["alumni", "engagement", "network"], img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 44, downloadUrl: "/resources-pdfs/rp-ad1.pdf" },

  // â”€â”€ Meetings & Operations Ã— Beginner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "mo-b1", title: "First Meeting Starter Pack", details: "Agenda template, icebreaker ideas, and ground rules checklist for running your very first club meeting.", type: "template", category: "Meetings & Operations", stage: "Beginner", downloads: 317, format: "DOCX", tags: ["first meeting", "agenda", "icebreakers"], img: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 95, downloadUrl: "/resources-pdfs/mo-b1.pdf" },
  // â”€â”€ Meetings & Operations Ã— Growing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "mo-gr1", title: "Committee Structure Guide", details: "How to divide your club into subcommittees â€” events, membership, comms â€” as you scale beyond founding members.", type: "guide", category: "Meetings & Operations", stage: "Growing", downloads: 188, format: "PDF", tags: ["committees", "structure", "organization"], img: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 53, downloadUrl: "/resources-pdfs/mo-gr1.pdf" },
  // â”€â”€ Meetings & Operations Ã— Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "mo-ad1", title: "Bylaws Amendment Procedures", details: "Formal process for proposing, debating, and ratifying changes to your club's governing bylaws.", type: "handbook", category: "Meetings & Operations", stage: "Advanced", downloads: 74, format: "PDF", tags: ["bylaws", "governance", "amendment"], img: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=600&q=80", rating: 4.4, saved: 28, downloadUrl: "/resources-pdfs/mo-ad1.pdf" },

  // â”€â”€ Events & Funding Ã— Beginner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ef-b1", title: "Micro-Event Planning Kit", details: "Checklist and budget template for planning your club's first small-scale event with minimal resources.", type: "checklist", category: "Events & Funding", stage: "Beginner", downloads: 224, format: "PDF", tags: ["events", "planning", "beginner"], img: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 67, downloadUrl: "/resources-pdfs/ef-b1.pdf" },
  // â”€â”€ Events & Funding Ã— Growing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ef-gr1", title: "Sponsorship Request Template", details: "Professional letter and pitch deck template for approaching local businesses and community sponsors.", type: "template", category: "Events & Funding", stage: "Growing", downloads: 276, format: "DOCX", tags: ["sponsorship", "fundraising", "letter"], img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 84, downloadUrl: "/resources-pdfs/ef-gr1.pdf" },
  // â”€â”€ Events & Funding Ã— Advanced â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ef-ad1", title: "Grant Writing Workbook", details: "Step-by-step workbook for researching, drafting, and submitting competitive education and community grants.", type: "guide", category: "Events & Funding", stage: "Advanced", downloads: 156, format: "PDF", tags: ["grants", "writing", "funding"], img: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80", rating: 4.8, saved: 61, downloadUrl: "/resources-pdfs/ef-ad1.pdf" },

  // â”€â”€ Leadership & Legacy Ã— Beginner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ll-b1", title: "First Officer Elections Guide", details: "How to nominate, campaign, and vote for your founding leadership team in a fair and transparent way.", type: "guide", category: "Leadership & Legacy", stage: "Beginner", downloads: 193, format: "PDF", tags: ["elections", "officers", "founding"], img: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80", rating: 4.6, saved: 55, downloadUrl: "/resources-pdfs/ll-b1.pdf" },
  // â”€â”€ Leadership & Legacy Ã— Growing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ll-gr1", title: "Mid-Year Leadership Check-In", details: "Structured self-assessment and peer review template for evaluating officer performance at the halfway point.", type: "template", category: "Leadership & Legacy", stage: "Growing", downloads: 134, format: "DOCX", tags: ["leadership", "review", "officers"], img: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=600&q=80", rating: 4.5, saved: 42, downloadUrl: "/resources-pdfs/ll-gr1.pdf" },
  // â”€â”€ Leadership & Legacy Ã— Active â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: "ll-a1", title: "Community Impact Tracker", details: "Spreadsheet and presentation template for documenting, measuring, and showcasing your club's community contributions.", type: "template", category: "Leadership & Legacy", stage: "Active", downloads: 167, format: "DOCX", tags: ["impact", "community", "reporting"], img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80", rating: 4.7, saved: 73, downloadUrl: "/resources-pdfs/ll-a1.pdf" },
];

export const CATEGORIES = ["All", "Getting Started", "Recruiting & Promoting", "Meetings & Operations", "Events & Funding", "Leadership & Legacy"];
export const STAGES = ["All Stages", "Beginner", "Growing", "Active", "Advanced"];

export const TYPE_COLORS: Record<ResourceType, string> = {
  guide:     "bg-blue-100 text-blue-700",
  template:  "bg-amber-100 text-amber-700",
  checklist: "bg-green-100 text-green-700",
  handbook:  "bg-purple-100 text-purple-700",
};

export const STAGE_COLORS: Record<string, string> = {
  "All Stages": "bg-primary-800 text-white",
  Beginner: "bg-emerald-100 text-emerald-800",
  Growing: "bg-blue-100 text-blue-800",
  Active: "bg-amber-100 text-amber-800",
  Advanced: "bg-purple-100 text-purple-800",
};